GrooveADT_testing:
  datasets:
    train: "datasets/GrooveADT_testing/0.0.0/train"
    test: "datasets/GrooveADT_testing/0.0.0/test"
    validation: "datasets/GrooveADT_testing/0.0.0/validation"
  evaluators:
    train: "evaluators/ADTEvaluator_0.0.0/GrooveADT_testing_train_0.0.0_evaluator.pickle"
    test: "evaluators/ADTEvaluator_0.0.0/GrooveADT_testing_test_0.0.0_evaluator.pickle"
    validation: "evaluators/ADTEvaluator_0.0.0/GrooveADT_testing_validation_0.0.0_evaluator.pickle"
GrooveADT:
  datasets:
    train: "datasets/GrooveADT/0.0.0/train"
    test: "datasets/GrooveADT/0.0.0/test"
    validation: "datasets/GrooveADT/0.0.0/validation"
  evaluators:
    train: "evaluators/ADTEvaluator_0.0.0/GrooveADT_train_0.0.0_evaluator.pickle"
    test: "evaluators/ADTEvaluator_0.0.0/GrooveADT_test_0.0.0_evaluator.pickle"
    validation: "evaluators/ADTEvaluator_0.0.0/GrooveADT_validation_0.0.0_evaluator.pickle"
GrooveVAE_testing:
  datasets:
    train: "datasets/GrooveVAE_testing/0.0.0/train"
    test: "datasets/GrooveVAE_testing/0.0.0/test"
    validation: "datasets/GrooveVAE_testing/0.0.0/validation"
  evaluators:
    train: "evaluators/VAEEvaluator_0.0.0/GrooveVAE_testing_train_0.0.0_evaluator.pickle"
    test: "evaluators/VAEEvaluator_0.0.0/GrooveVAE_testing_test_0.0.0_evaluator.pickle"
    validation: "evaluators/VAEEvaluator_0.0.0/GrooveVAE_testing_validation_0.0.0_evaluator.pickle"
GrooveVAE:
  datasets:
    train: "datasets/GrooveVAE/0.0.0/train"
    test: "datasets/GrooveVAE/0.0.0/test"
    validation: "datasets/GrooveVAE/0.0.0/validation"
  evaluators:
    train: "evaluators/VAEEvaluator_0.0.0/GrooveVAE_train_0.0.0_evaluator.pickle"
    test: "evaluators/VAEEvaluator_0.0.0/GrooveVAE_test_0.0.0_evaluator.pickle"
    validation: "evaluators/VAEEvaluator_0.0.0/GrooveVAE_validation_0.0.0_evaluator.pickle"
